---
name: devcontainer-features-documentation
on:
  workflow_call:
    inputs:
      gh_app_id:
        description: GitHub App ID
        required: true
        type: string
      owner:
        description: GitHub App installation owner. Defaults to repository owner. If 'owner' is set and 'repositories' is empty, access will be scoped to all repositories in the provided repository owner's installation. If 'owner' and 'repositories' are empty, access will be scoped only to the current repository.
        required: false
        type: string
      repositories:
        description: Comma-separated list of repositories to grant access to. If 'owner' is set and 'repositories' is empty, access will be scoped to all repositories in the provided repository owner's installation. If 'owner' and 'repositories' are empty, access will be scoped only to the current repository.
        required: false
        type: string
    secrets:
      gh_app_private_key:
        description: GitHub App private key
        required: true

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v2
        id: app_token
        with:
          app-id: ${{ inputs.gh_app_id }}
          private-key: ${{ secrets.gh_app_private_key }}
          owner: ${{ inputs.owner }}
          repositories: ${{ inputs.repositories }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate documentation
        uses: devcontainers/action@v1
        with:
          generate-docs: true
          base-path-to-features: ./src

      - name: Detect README changes
        uses: tj-actions/verify-changed-files@v20
        id: changes
        with:
          files: |
            src/**/README.md

      - name: Create pull request
        if: steps.changes.outputs.files_changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          branch: automated-documentation-update
          sign-commits: true
          token: ${{ steps.app_token.outputs.token }}
          title: "Automated documentation update"
