---
name: check

on:
  workflow_call:
    inputs:
      allowed_skips:
        description: "Job names that are allowed to be skipped and not affect the outcome, as a comma-separated list."
        required: false
        type: string
      jobs:
        description: "Must be exactly 'toJSON(needs)' in the calling workflow."
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check status of needed jobs and pass/fail
        uses: re-actors/alls-green@v1.2.2
        with:
          allowed-skips: ${{ inputs.allowed_skips }}
          jobs: ${{ inputs.jobs }}
