---
name: github-action-update-readme

on:
  workflow_call:
    inputs:
      gh_app_id:
        description: GitHub App ID
        required: true
        type: string
      owner:
        description: GitHub App installation owner. Defaults to repository owner. If 'owner' is set and 'repositories' is empty, access will be scoped to all repositories in the provided repository owner's installation. If 'owner' and 'repositories' are empty, access will be scoped only to the current repository.
        required: false
        type: string
      repositories:
        description: Comma-separated list of repositories to grant access to. If 'owner' is set and 'repositories' is empty, access will be scoped to all repositories in the provided repository owner's installation. If 'owner' and 'repositories' are empty, access will be scoped only to the current repository.
        required: false
        type: string
      readme_file_name:
        description: Filename for the README file.
        required: false
        default: README.md
        type: string
    secrets:
      gh_app_private_key:
        description: GitHub App private key
        required: true

jobs:
  github-action-update-readme:
    runs-on: ubuntu-24.04
    steps:
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app-id: ${{ inputs.gh_app_id }}
          private-key: ${{ secrets.gh_app_private_key }}
          owner: ${{ inputs.owner }}
          repositories: ${{ inputs.repositories }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app_token.outputs.token }}

      - name: Update README
        uses: npalm/action-docs-action@v3.1.1

      - name: Detect README changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          base: HEAD
          filters: |
            readme:
              - "README.md"
          token: ${{ steps.app_token.outputs.token }}

      # - name: timeout
      #   if: steps.changes.outputs.readme == 'true'
      #   env:
      #     GH_TOKEN: ${{ steps.app_token.outputs.token }}
      #   run: |
      #     BLOB_SHA=$(gh api --method GET -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/contents/${{ inputs.readme_file_name }} -q .sha)
      #     exit 1
      #   shell: bash

      # https://www.zufallsheld.de/2023/12/11/til-how-to-create-github-files-via-api/
      # https://gist.github.com/swinton/03e84635b45c78353b1f71e41007fc7c
      - name: Sign and commit README changes
        if: steps.changes.outputs.readme == 'true'
        env:
          GH_TOKEN: ${{ steps.app_token.outputs.token }}
        run: |
          BLOB_SHA="$(gh api --method GET -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/contents/${{ inputs.readme_file_name }}?ref=${{ github.head_ref }} -q .sha)"
          MESSAGE="docs: Automated README update"
          gh api --method PUT -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/contents/${{ inputs.readme_file_name }} --field message="$MESSAGE" --field content=@<(base64 -i ${{ inputs.readme_file_name }}) --field branch="${{ github.head_ref }}" --field sha="$BLOB_SHA"
        shell: bash
