---
name: github-detect-changes

on:
  workflow_call:
    inputs:
      filter_file_path:
        description: Path to a YAML file populated with filters.
        required: false
        default: .github/filters.yml
        type: string
    outputs:
      changes:
        description: JSON array with names of filters matching changed files.
        value: ${{ jobs.detect.outputs.changes }}

jobs:
  detect:
    runs-on: ubuntu-24.04
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Detect changed paths
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.0
        id: filter
        with:
          filters: ${{ inputs.filter_file_path }}
