---
name: updatecli

on:
  workflow_call:
    inputs:
      automerge_config:
        description: Path to the updatecli automerge manifest file.
        required: true
        type: string
      breaking_config:
        description: Path to the updatecli breaking-change manifest file.
        required: true
        type: string
      values:
        description: Path to the updatecli values file.
        required: true
        type: string
      gh_app_id:
        description: GitHub App ID.
        required: true
        type: string
    secrets:
      gh_app_private_key:
        description: GitHub App private key.
        required: true

jobs:
  automerge:
    runs-on: ubuntu-24.04
    steps:
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app_token
        with:
          app-id: ${{ inputs.gh_app_id }}
          private-key: ${{ secrets.gh_app_private_key }}
          permission-contents: write
          permission-pull-requests: write

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install updatecli
        uses: updatecli/updatecli-action@4b17f4ea784de29f71f85f9bc4955402ba1ae53c # v2.100.0

      - name: Run updatecli (automerge)
        run: updatecli apply --config "${{ inputs.automerge_config }}" --values "${{ inputs.values }}"
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
          UPDATECLI_GITHUB_USERNAME: x-access-token

  breaking:
    runs-on: ubuntu-24.04
    steps:
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app_token
        with:
          app-id: ${{ inputs.gh_app_id }}
          private-key: ${{ secrets.gh_app_private_key }}
          permission-contents: write
          permission-pull-requests: write

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install updatecli
        uses: updatecli/updatecli-action@4b17f4ea784de29f71f85f9bc4955402ba1ae53c # v2.100.0

      - name: Run updatecli (breaking)
        continue-on-error: true # Expected to fail when no breaking versions exist
        run: updatecli apply --config "${{ inputs.breaking_config }}" --values "${{ inputs.values }}"
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
          UPDATECLI_GITHUB_USERNAME: x-access-token
